### ISSUE TITLE
make it possible to test against pipeline

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog-plugin-pipeline-processor#58]
### Problem description

if you have a message that is already in your system you can use the new simulator to check how this message would look after the pipelines.

It would be nice to have the ability to "test against pipeline" like you have with streams.

![graylog_web_interface](https://cloud.githubusercontent.com/assets/404238/17173517/94f5bb28-53fb-11e6-94b1-7a837f893283.png)

This could be just a link to the simulator with the message details already filled in.

**Comment by edmundoa** [comment]
Just to add a bit of context: testing existing (and processed) messages against a pipeline is not that helpful in most cases, as some changes will be hidden because they were already applied in the message.

That's the reason why we currently only support loading raw messages in the pipeline simulator.

**Comment by jalogisch** [comment]
maybe this could be a function if you have stored the **full message** ? from the input?

**Comment by kroepke** [comment]
I don't think this is generally useful, because already processed messages won't usually match again.
Even the "test against stream" is of dubious value IMHO, because the workflow is backwards: When building a stream you want to pick messages, or paste them, to build your processing rules, testing after the fact implies that changes would affect those messages, which they don't.

It's just that at the moment we don't have a better way.

**Comment by kroepke** [comment]
We are not likely to implement this, as the workflow is backwards, and as previously mentioned most of the changes were already applied.
We need to solve this in a more generic manner, rather than adding another button.
