### ISSUE TITLE
Not easy to work with unknown JSON schemas

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-pipeline-processor#80]
Parsing JSON already works with the current pipelines but it is not easy to work with JSON that has a very flexible schema that can differ a little from message to message.

For example, when parsing OSSEC logs, messages representing SSH logins will have a `acct` and `src_ip` field. Messages representing changed files will not have those fields, but `md5_old`, `md5_new`, and `file`. There are many more fields that I am not aware of yet.

Handling all this with the current explicit way of adding JSON tree fields to message fields is almost impossible. I'd like to have a `set_all_fields($json_tree)` message or something similar.

Important: Make sure that the keys in the JSON tree do not overwrite standard message fields like `_id`, `source`, `level` etc...

**Comment by kroepke** [comment]
This is not quite the expected use case for pipeline rules.

I realize that it is painful to type everything out, but this is what the rule language was designed for: It is not designed to be a high level language, rather it contains the building blocks to be able to implement data extraction.

If the messages have a different shape they are not intended to be processed by the same rules, e.g. in this case the OSSEC pipeline for SSH logins will be different from the one dealing with files. They might contain some common rules (e.g. the gating ones deciding whether this is in fact an OSSEC log), and it will use more stages to guide the processing.

Setting the fields is simply using the internal API for doing so, if that prevents setting certain fields, then that's what's happening. Again, the rule language is not designed to be exposed like this to end users (even though it currently is). Specifically it is not designed to prevent these things, because we wanted flexibility and not complete safety.

**Comment by lennartkoopmann** [comment]
Ok, this is something similar to what I did with the Kippo Honeypot rules. Let me see if there is a way to handle it that way.

Thanks!

**Comment by alpha-centauri** [comment]
@kroepke I don't quite get your point. This behaviour is already implemented as extractor (see https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/inputs/extractors/JsonExtractor.java). So I don't see a reason why this shouldn't be the case for pipeline functions.
